package gymmanagement;

import gymmanagement.HomePageGUI.*;
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author PC
 */
public class ManagerChangePasswordGUI extends javax.swing.JFrame {

    public static String old;
    public static String newp;

    boolean ddOpen = false;

    String url = "jdbc:mysql://localhost:3306/gym_db";

    String user = "root";
    String password = "";

    Connection conn;
    Statement myStmt;

    public ManagerChangePasswordGUI() {
        initComponents();

        x.setVisible(false);
        passwordError.setVisible(false);
        lengthError.setVisible(false);
        mismatchError.setVisible(false);
        sameError.setVisible(false);
        fillAll.setVisible(false);

       

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        sameError = new javax.swing.JLabel();
        conpass = new javax.swing.JPasswordField();
        newpass = new javax.swing.JPasswordField();
        oldpass = new javax.swing.JPasswordField();
        x = new javax.swing.JLabel();
        x1 = new javax.swing.JLabel();
        mismatchError = new javax.swing.JLabel();
        lengthError = new javax.swing.JLabel();
        passwordError = new javax.swing.JLabel();
        fillAll = new javax.swing.JLabel();
        background = new javax.swing.JLabel();
        nextBtn = new javax.swing.JButton();
        xBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setMinimumSize(new java.awt.Dimension(773, 448));
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(null);

        sameError.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        sameError.setForeground(new java.awt.Color(192, 0, 0));
        sameError.setText("* New password cannot be the same as old password *");
        getContentPane().add(sameError);
        sameError.setBounds(220, 265, 300, 13);

        conpass.setBackground(new java.awt.Color(56, 85, 98));
        conpass.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        conpass.setForeground(new java.awt.Color(255, 255, 255));
        conpass.setBorder(null);
        conpass.setSelectionColor(new java.awt.Color(56, 85, 98));
        conpass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                conpassActionPerformed(evt);
            }
        });
        getContentPane().add(conpass);
        conpass.setBounds(380, 282, 170, 30);

        newpass.setBackground(new java.awt.Color(56, 85, 98));
        newpass.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        newpass.setForeground(new java.awt.Color(255, 255, 255));
        newpass.setBorder(null);
        newpass.setSelectionColor(new java.awt.Color(56, 85, 98));
        getContentPane().add(newpass);
        newpass.setBounds(350, 230, 200, 30);

        oldpass.setBackground(new java.awt.Color(56, 85, 98));
        oldpass.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        oldpass.setForeground(new java.awt.Color(255, 255, 255));
        oldpass.setBorder(null);
        oldpass.setSelectionColor(new java.awt.Color(56, 85, 98));
        getContentPane().add(oldpass);
        oldpass.setBounds(340, 175, 210, 30);

        x.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gymmanagement/x.PNG"))); // NOI18N
        getContentPane().add(x);
        x.setBounds(720, 0, 60, 60);

        x1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gymmanagement/xwhite.PNG"))); // NOI18N
        getContentPane().add(x1);
        x1.setBounds(700, 10, 60, 40);

        mismatchError.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        mismatchError.setForeground(new java.awt.Color(192, 0, 0));
        mismatchError.setText("* Passwords do not match*");
        getContentPane().add(mismatchError);
        mismatchError.setBounds(220, 315, 300, 20);

        lengthError.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        lengthError.setForeground(new java.awt.Color(192, 0, 0));
        lengthError.setText("* Password must be atleast 6 characters long*");
        getContentPane().add(lengthError);
        lengthError.setBounds(220, 265, 300, 13);

        passwordError.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        passwordError.setForeground(new java.awt.Color(192, 0, 0));
        passwordError.setText("* Incorrect password *");
        getContentPane().add(passwordError);
        passwordError.setBounds(220, 210, 300, 13);

        fillAll.setForeground(new java.awt.Color(192, 0, 0));
        fillAll.setText("* Please fill all fields *");
        getContentPane().add(fillAll);
        fillAll.setBounds(330, 420, 300, 14);

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gymmanagement/ChangePassword.PNG"))); // NOI18N
        getContentPane().add(background);
        background.setBounds(0, 0, 780, 450);

        nextBtn.setText("jButton1");
        nextBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                nextBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                nextBtnMouseExited(evt);
            }
        });
        nextBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextBtnActionPerformed(evt);
            }
        });
        getContentPane().add(nextBtn);
        nextBtn.setBounds(310, 370, 160, 50);

        xBtn.setText("jButton1");
        xBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                xBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                xBtnMouseExited(evt);
            }
        });
        xBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                xBtnActionPerformed(evt);
            }
        });
        getContentPane().add(xBtn);
        xBtn.setBounds(719, 19, 20, 20);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    boolean checkPass() {
        
        try {
            
            conn = DriverManager.getConnection(url, user, password);
            myStmt = conn.createStatement();
            
            String sql = "select password from Manager where ManagerID = '" + LoginGUI.managerid + "';";
            ResultSet rs = myStmt.executeQuery(sql);

            while (rs.next()) {

                String p = rs.getString("password");
                
                if (p.equals(old)) {
                    return true;
                }

            }
            
            return false;

        } catch (SQLException ex) {
            Logger.getLogger(ManagerChangePasswordGUI.class.getName()).log(Level.SEVERE, null, ex);
        }
        return false;
    }


    private void conpassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_conpassActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_conpassActionPerformed

    private void nextBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextBtnActionPerformed

        fillAll.setVisible(false);
        passwordError.setVisible(false);
        mismatchError.setVisible(false);
        sameError.setVisible(false);

        old = new String(oldpass.getPassword());
        newp = new String(newpass.getPassword());
        String confirm = new String(conpass.getPassword());

        boolean isEmpty = old.equals("") || newp.equals("") || confirm.equals("");

        if (isEmpty) {
            fillAll.setVisible(true);
        }

        else if (!checkPass()) {
            passwordError.setVisible(true);
        }

        else if (newp.equals(old)) {
            sameError.setVisible(true);
        }

        else if (newp.length() < 6) {
            lengthError.setVisible(true);
        }

        else if (!confirm.equals(newp)) {
            mismatchError.setVisible(true);
        }

        else {

            Methods m = new Methods();
            m.updateManager("password", newp, LoginGUI.managerid);
            this.setVisible(false);
        }
    }//GEN-LAST:event_nextBtnActionPerformed

    private void nextBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nextBtnMouseExited

    }//GEN-LAST:event_nextBtnMouseExited

    private void nextBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nextBtnMouseEntered

    }//GEN-LAST:event_nextBtnMouseEntered

    private void xBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_xBtnMouseEntered
        x.setVisible(true);
    }//GEN-LAST:event_xBtnMouseEntered

    private void xBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_xBtnMouseExited
        x.setVisible(false);
    }//GEN-LAST:event_xBtnMouseExited

    private void xBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_xBtnActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_xBtnActionPerformed

    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel background;
    public javax.swing.JPasswordField conpass;
    private javax.swing.JLabel fillAll;
    private javax.swing.JLabel lengthError;
    private javax.swing.JLabel mismatchError;
    public javax.swing.JPasswordField newpass;
    private javax.swing.JButton nextBtn;
    public javax.swing.JPasswordField oldpass;
    private javax.swing.JLabel passwordError;
    private javax.swing.JLabel sameError;
    private javax.swing.JLabel x;
    private javax.swing.JLabel x1;
    private javax.swing.JButton xBtn;
    // End of variables declaration//GEN-END:variables
}
