/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gymmanagement;

import static gymmanagement.MemberBankDetailsGUI.bankTable;
import java.sql.*;
import java.text.DecimalFormat;
import java.time.LocalDate;
import java.time.Month;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author PC
 */
public class MemberAccountDetailsGUI extends javax.swing.JFrame {

    public static String namee;
    public static String number;
    public static int m;
    public static int y;
    public static String CVV;
    String mid = "";

    String url = "jdbc:mysql://localhost:3306/gym_db";

    String user = "root";
    String password = "";

    Connection conn;
    Statement myStmt;

    public MemberAccountDetailsGUI() {
        initComponents();

        fillAll.setVisible(false);
        monthError.setVisible(false);
        cvvError.setVisible(false);
        accError.setVisible(false);
        accError1.setVisible(false);

        x.setVisible(false);
        

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        monthError = new javax.swing.JLabel();
        accError1 = new javax.swing.JLabel();
        accError = new javax.swing.JLabel();
        cvvError = new javax.swing.JLabel();
        year = new javax.swing.JComboBox<>();
        month = new javax.swing.JComboBox<>();
        fillAll = new javax.swing.JLabel();
        cvv = new javax.swing.JTextField();
        accNum = new javax.swing.JTextField();
        name = new javax.swing.JTextField();
        x = new javax.swing.JLabel();
        x1 = new javax.swing.JLabel();
        background = new javax.swing.JLabel();
        xBtn = new javax.swing.JButton();
        nextBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setMinimumSize(new java.awt.Dimension(764, 435));
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(764, 435));
        setResizable(false);
        getContentPane().setLayout(null);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gymmanagement/card no.PNG"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(206, 230, 130, 30);

        jPanel4.setBackground(new java.awt.Color(56, 85, 98));
        getContentPane().add(jPanel4);
        jPanel4.setBounds(0, 0, 762, 2);

        jPanel3.setBackground(new java.awt.Color(56, 85, 98));
        getContentPane().add(jPanel3);
        jPanel3.setBounds(0, 433, 761, 2);

        jPanel2.setBackground(new java.awt.Color(56, 85, 98));
        getContentPane().add(jPanel2);
        jPanel2.setBounds(761, 0, 2, 440);

        jPanel1.setBackground(new java.awt.Color(56, 85, 98));
        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 2, 440);

        monthError.setForeground(new java.awt.Color(192, 0, 0));
        monthError.setText("* Enter valid expiry date *");
        getContentPane().add(monthError);
        monthError.setBounds(200, 322, 300, 14);

        accError1.setForeground(new java.awt.Color(192, 0, 0));
        accError1.setText("* Enter a unique card number *");
        getContentPane().add(accError1);
        accError1.setBounds(200, 266, 300, 14);

        accError.setForeground(new java.awt.Color(192, 0, 0));
        accError.setText("* Enter valid Card Number *");
        getContentPane().add(accError);
        accError.setBounds(200, 266, 300, 14);

        cvvError.setForeground(new java.awt.Color(192, 0, 0));
        cvvError.setText("* Enter valid CVV *");
        getContentPane().add(cvvError);
        cvvError.setBounds(200, 380, 300, 14);

        year.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        year.setForeground(new java.awt.Color(56, 85, 98));
        year.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2021", "2022", "2023", "2024", "2025", "2026", "2027", "2028", "2029", "2030", "2031", "2032", "2033", "2034", "2035", "2036", "2037", "2038", "2039", "2040", "2041" }));
        year.setBorder(null);
        year.setLightWeightPopupEnabled(false);
        year.setMinimumSize(new java.awt.Dimension(170, 35));
        year.setName("Gender"); // NOI18N
        year.setPreferredSize(new java.awt.Dimension(170, 35));
        year.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                yearActionPerformed(evt);
            }
        });
        getContentPane().add(year);
        year.setBounds(490, 286, 70, 30);

        month.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        month.setForeground(new java.awt.Color(56, 85, 98));
        month.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12" }));
        month.setBorder(null);
        month.setLightWeightPopupEnabled(false);
        month.setMinimumSize(new java.awt.Dimension(150, 35));
        month.setName("Gender"); // NOI18N
        month.setPreferredSize(new java.awt.Dimension(150, 35));
        month.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                monthActionPerformed(evt);
            }
        });
        getContentPane().add(month);
        month.setBounds(310, 286, 60, 30);

        fillAll.setForeground(new java.awt.Color(192, 0, 0));
        fillAll.setText("* Please fill all fields *");
        getContentPane().add(fillAll);
        fillAll.setBounds(440, 390, 300, 14);

        cvv.setBackground(new java.awt.Color(56, 85, 98));
        cvv.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cvv.setForeground(new java.awt.Color(255, 255, 255));
        cvv.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        cvv.setBorder(null);
        cvv.setCaretColor(new java.awt.Color(255, 255, 255));
        cvv.setSelectionColor(new java.awt.Color(255, 255, 255));
        cvv.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cvvMouseClicked(evt);
            }
        });
        cvv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cvvActionPerformed(evt);
            }
        });
        cvv.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                cvvKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                cvvKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                cvvKeyTyped(evt);
            }
        });
        getContentPane().add(cvv);
        cvv.setBounds(250, 345, 110, 30);

        accNum.setBackground(new java.awt.Color(56, 85, 98));
        accNum.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        accNum.setForeground(new java.awt.Color(255, 255, 255));
        accNum.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        accNum.setBorder(null);
        accNum.setCaretColor(new java.awt.Color(255, 255, 255));
        accNum.setSelectionColor(new java.awt.Color(255, 255, 255));
        accNum.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                accNumMouseClicked(evt);
            }
        });
        accNum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                accNumActionPerformed(evt);
            }
        });
        accNum.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                accNumKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                accNumKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                accNumKeyTyped(evt);
            }
        });
        getContentPane().add(accNum);
        accNum.setBounds(340, 230, 220, 30);

        name.setBackground(new java.awt.Color(56, 85, 98));
        name.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        name.setForeground(new java.awt.Color(255, 255, 255));
        name.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        name.setBorder(null);
        name.setCaretColor(new java.awt.Color(255, 255, 255));
        name.setSelectionColor(new java.awt.Color(255, 255, 255));
        name.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                nameMouseClicked(evt);
            }
        });
        name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameActionPerformed(evt);
            }
        });
        name.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                nameKeyPressed(evt);
            }
        });
        getContentPane().add(name);
        name.setBounds(350, 172, 210, 30);

        x.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gymmanagement/x.PNG"))); // NOI18N
        getContentPane().add(x);
        x.setBounds(730, -10, 60, 60);

        x1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gymmanagement/xwhite.PNG"))); // NOI18N
        getContentPane().add(x1);
        x1.setBounds(712, 0, 60, 40);

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gymmanagement/Account details.PNG"))); // NOI18N
        getContentPane().add(background);
        background.setBounds(0, -30, 770, 495);

        xBtn.setText("jButton1");
        xBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                xBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                xBtnMouseExited(evt);
            }
        });
        xBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                xBtnActionPerformed(evt);
            }
        });
        getContentPane().add(xBtn);
        xBtn.setBounds(735, 10, 20, 20);

        nextBtn.setText("jButton1");
        nextBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                nextBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                nextBtnMouseExited(evt);
            }
        });
        nextBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextBtnActionPerformed(evt);
            }
        });
        getContentPane().add(nextBtn);
        nextBtn.setBounds(400, 340, 170, 50);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void xBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_xBtnActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_xBtnActionPerformed

    private void xBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_xBtnMouseEntered
        x.setVisible(true);
    }//GEN-LAST:event_xBtnMouseEntered

    private void xBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_xBtnMouseExited
        x.setVisible(false);
    }//GEN-LAST:event_xBtnMouseExited

    
    void updateTable() {
        
        int c;
        
        try {            
            Connection myConn = DriverManager.getConnection(url, user, password);
            Statement myStmt = myConn.createStatement();
            
            String sql = "SELECT `CardNum`, `ExpiryMonth`, `ExpiryYear`, "
                    + "`CardHoldersName`, `DefaultCard` FROM `bankdetails`"
                    + "WHERE PersonID = '" + LoginGUI.memberid + "';";
            ResultSet rs = myStmt.executeQuery(sql);
            
            ResultSetMetaData rsd = rs.getMetaData();
            c = rsd.getColumnCount();
            DefaultTableModel dft = (DefaultTableModel)bankTable.getModel();
            dft.setRowCount(0);
            
            while(rs.next()) {
                Vector v2 = new Vector();
                
                for(int i = 1; i <= c; i++) {
                    v2.add(rs.getString("CardNum"));
                    v2.add(rs.getString("CardHoldersName"));
                    
                    String exp = rs.getString("ExpiryMonth") + "/" + rs.getString("ExpiryYear");
                    v2.add(exp);
                    
                    if(rs.getInt("DefaultCard") == 1)
                        v2.add("Default");
                    else
                        v2.add("");
                }
                
                dft.addRow(v2);
            }
        } 
        
        catch (SQLException ex) {
            Logger.getLogger(MemberBankDetailsGUI.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    
    
    
    private void nextBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextBtnActionPerformed

        accError.setVisible(false);
        monthError.setVisible(false);
        cvvError.setVisible(false);
        fillAll.setVisible(false);
        accError1.setVisible(false);

        LocalDate currentdate = LocalDate.now();
        int currentMonth = currentdate.getMonthValue();
        int currentYear = currentdate.getYear();

        namee = name.getText();
        number = accNum.getText();
        m = Integer.parseInt(month.getItemAt(month.getSelectedIndex()));
        y = Integer.parseInt(year.getItemAt(year.getSelectedIndex()));
        CVV = cvv.getText();

        boolean isEmpty = namee.equals("") || number.equals("") || cvv.getText().equals("");

        if (isEmpty) {
            fillAll.setVisible(true);
        } 
        else if (number.length() != 16) {
            accError.setVisible(true);
        } 
        else if (CVV.length() != 3) {
            cvvError.setVisible(true);
        } 
        
        else if (y <= currentYear) {
            monthError.setVisible(true);
        } else if (y == currentYear && m <= currentMonth) {
            monthError.setVisible(true);
        } 
        
        else {
//            HomePageGUI.s3.setVisible(true);
            addBankDetails();
            updateTable();
            this.setVisible(false);
        }

//        LoginGUI.memberid = mid;
        
        

    }//GEN-LAST:event_nextBtnActionPerformed

    void addBankDetails() {

        accError1.setVisible(false);
        
        try {
            conn = DriverManager.getConnection(url, user, password);
            myStmt = conn.createStatement();

            String sql = "INSERT INTO `bankdetails`(`PersonID`, `CardNum`, "
                    + "`CVV`, `ExpiryMonth`, `ExpiryYear`, `CardHoldersName`, `DefaultCard`) "
                    + "VALUES ('" + LoginGUI.memberid + "','" + number + "','" + CVV + "',"
                    + "'" + m + "','" + y + "','" + namee + "', '0');";
            int rs = myStmt.executeUpdate(sql);
        } 
        
        
        catch (SQLIntegrityConstraintViolationException e) {
            accError1.setVisible(true);
        }
        catch (SQLException ex) {
            Logger.getLogger(MemberAccountDetailsGUI.class.getName()).log(Level.SEVERE, null, ex);
        }
        
         
    }


    private void nextBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nextBtnMouseEntered

    }//GEN-LAST:event_nextBtnMouseEntered

    private void nextBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nextBtnMouseExited

    }//GEN-LAST:event_nextBtnMouseExited

    private void nameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nameMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_nameMouseClicked

    private void nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameActionPerformed

    private void cvvMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cvvMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_cvvMouseClicked

    private void cvvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cvvActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cvvActionPerformed

    private void accNumMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_accNumMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_accNumMouseClicked

    private void accNumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_accNumActionPerformed
        name.setVisible(true);
    }//GEN-LAST:event_accNumActionPerformed

    private void accNumKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_accNumKeyTyped

    }//GEN-LAST:event_accNumKeyTyped

    private void cvvKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cvvKeyTyped

    }//GEN-LAST:event_cvvKeyTyped

    private void accNumKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_accNumKeyReleased

    }//GEN-LAST:event_accNumKeyReleased

    private void cvvKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cvvKeyReleased
        // TODO add your handling code here:
//        h = Integer.parseInt(height.getText());
//        BMI = (w / (h*h)) * 10000;
//        bmi.setText(BMI+"");
    }//GEN-LAST:event_cvvKeyReleased

    private void nameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nameKeyPressed

    }//GEN-LAST:event_nameKeyPressed

    private void accNumKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_accNumKeyPressed
        char c = evt.getKeyChar();
        if (Character.isDigit(c) || evt.getKeyCode() == 8) {
            accNum.setEditable(true);
        } else {
            accNum.setEditable(false);
        }
    }//GEN-LAST:event_accNumKeyPressed

    private void cvvKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cvvKeyPressed
        char c = evt.getKeyChar();
        if (Character.isDigit(c) || evt.getKeyCode() == 8) {
            cvv.setEditable(true);
        } else {
            cvv.setEditable(false);
        }
    }//GEN-LAST:event_cvvKeyPressed

    private void monthActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_monthActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_monthActionPerformed

    private void yearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yearActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_yearActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MemberAccountDetailsGUI.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MemberAccountDetailsGUI.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MemberAccountDetailsGUI.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MemberAccountDetailsGUI.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MemberAccountDetailsGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel accError;
    private javax.swing.JLabel accError1;
    public javax.swing.JTextField accNum;
    private javax.swing.JLabel background;
    public javax.swing.JTextField cvv;
    private javax.swing.JLabel cvvError;
    private javax.swing.JLabel fillAll;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    public javax.swing.JComboBox<String> month;
    private javax.swing.JLabel monthError;
    public javax.swing.JTextField name;
    private javax.swing.JButton nextBtn;
    private javax.swing.JLabel x;
    private javax.swing.JLabel x1;
    private javax.swing.JButton xBtn;
    public javax.swing.JComboBox<String> year;
    // End of variables declaration//GEN-END:variables
}
